<?php
	get_header();
	get_template_part('index-video');
	get_template_part('grid/index');
	get_template_part('grid/editorials');
	get_template_part('index-about');
	get_template_part('instagram');
	get_footer();
?>
