<?php
	get_header();
	get_template_part('home/landing');
	get_template_part('grid/index');
	get_template_part('grid/editorials');
	get_template_part('home/about');
	get_template_part('grid/instagram');
	get_footer();
?>
